// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"database/sql"
	"time"
)

type Book struct {
	ID          int64     `json:"id"`
	Title       string    `json:"title"`
	Author      string    `json:"author"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	Count       int64     `json:"count"`
}

type Transaction struct {
	ID        int64         `json:"id"`
	UserID    sql.NullInt64 `json:"user_id"`
	BookID    sql.NullInt64 `json:"book_id"`
	CreatedAt time.Time     `json:"created_at"`
	// negative for borrow and positive for return
	Count sql.NullInt64 `json:"count"`
}

type User struct {
	ID        int64     `json:"id"`
	FirstName string    `json:"first_name"`
	CreatedAt time.Time `json:"created_at"`
}
